### ISSUE TITLE
Approved! Firm engagement Chore 2 for domain.com [ApprovedPMChoreStep2]

### ISSUE THREAD

**Issue by puneetlath** [puneetlath/test#117]
- [ ] I sent a message to my firm in the #domain room offering an accountant training webinar (Point 1 of [SO](https://stackoverflow.com/c/expensify/questions/14783/14784#14784))
- [ ] I have set a date for the accountant training 
- [ ] I have confirmed a list of accountant attendee emails for the training with the firm (Point 3 of [SO](https://stackoverflow.com/c/expensify/questions/14783/14784#14784))
- [ ] I have used the appropriate presentation deck below and completed the training webinar.
    - A: [US firm](https://docs.google.com/presentation/d/1z4XRtdPW1syKc7KUE-CwCWGWTU7KOPeLzj5lr5vOuII/edit#slide=id.gd4654fd11d_0_263)
    - B: [International firm](https://docs.google.com/presentation/d/1bRx0_45xFLHvRC-xjRWwM2SdZ45KO8FDyBHP9IAuTJw/edit#slide=id.gd4654fd11d_0_263)
- [ ] I have shared the training follow up (Point 6 of [SO](https://stackoverflow.com/c/expensify/questions/14783/14784#14784)) and I understand the criteria for a Lunch & Learn meeting ([SO](https://stackoverflowteams.com/c/expensify/questions/15159/15160#15160))
- [ ] I have sent swag t-shirts requested by training attendees ([SO](https://stackoverflow.com/c/expensify/questions/3015))

Once you’ve completed all check-points above, simply close this out to open your new chore for this firm.
